package com.redutec.core.meta;

import lombok.Getter;
import lombok.RequiredArgsConstructor;

import java.util.List;

import static com.redutec.core.meta.Domain.*;

@Getter
@RequiredArgsConstructor
public enum CategoryValue {
    LBV001("EDUCATION", "교육자료", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    LBV002("CONSULTING", "상담자료", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    LBV003("PROMOTION", "홍보자료", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    LBV004("ETC", "기타", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    LBV005("READING_NOTE", "독서기록장", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    LBV006("READING_LIST", "독서목록", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    FCV001("USER_INFO", "회원정보", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    FCV002("DIAGNOSIS", "독서진단", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, READING_OCEAN_SCHOOL)),
    FCV003("RECOMMENDED_BOOK", "추천도서", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, READING_OCEAN_SCHOOL)),
    FCV004("AFTER_READING", "독후활동", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, READING_OCEAN_SCHOOL)),
    FCV005("LIBRARY", "나의 서재", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, READING_OCEAN_SCHOOL)),
    FCV006("COMMUNITY", "커뮤니티", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, READING_OCEAN_SCHOOL)),
    FCV007("ETC", "기타", List.of(READING_OCEAN_EDU, READING_OCEAN_HOME, TEACHING_OCEAN, READING_OCEAN_SCHOOL, TEACHING_OCEAN_SCHOOL)),
    FCV008("ACADEMIC_MANAGEMENT", "학사관리", List.of(TEACHING_OCEAN, TEACHING_OCEAN_SCHOOL)),
    FCV009("CLASS_MANAGEMENT", "학급관리", List.of(TEACHING_OCEAN, TEACHING_OCEAN_SCHOOL)),
    FCV010("READING_OCEAN_MALL", "리딩오션몰", List.of(TEACHING_OCEAN, TEACHING_OCEAN_SCHOOL)),
    FCV011("PAYMENT", "이용료 결제", List.of(TEACHING_OCEAN, TEACHING_OCEAN_SCHOOL));;

    private final String name;
    private final String description;
    private final List<Domain> allowedDomainList;
}