# server
server:
  port: 28084
  error:
    path: /error
  servlet:
    context-path: /api/teaching-ocean
    session:
      timeout: 1440m
# Spring
spring:
  application:
    name: teaching-ocean
  profiles:
    group:
      local: core
      dev: core
      prod: core
  servlet:
    multipart:
      max-file-size: 1000MB
      max-request-size: 1000MB
  datasource:
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      leak-detection-threshold: 30000
      maxLifetime: 1800000
      idleTimeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        globally_quoted_identifiers: true
  mail:
    host: smtp.mailplug.co.kr
    port: 465
    username: info@redutec.co.kr
    password: redutec77$
# Logger Properties
logging:
  level:
    root: info
    org.hibernate: info
    org.hibernate.SQL: off
    org.hibernate.type.descriptor.sql.BasicBinder: off
    org.hibernate.orm.jdbc.bind: off
    log4jdbc: off
    jdbc:
      sqlonly: warn
      sqltiming: off
      audit: off
      connection: off
      resultset: off
      resultsettable: off
      sqlerror: warn
  file:
    name: ./logs/teaching-ocean.log
# Security
jwt:
  secret: "re@ding0ce@n#123TeachingOceanJsonWebTokenSecret"
  access-token-expiration: 60000
  refresh-token-expiration: 37600000
aes-256-key: "wI9a1XcwVlxiZklgK+P73P7msAVd4eHro3+cdk8pKxU="

---
# local
spring:
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/redutec?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&useInformationSchema=true&autoReconnect=true
    username: "redutec"
    password: "readingocean2022"
# Custom
front-end-server: 127.0.0.1
file:
  baseUrl: http://localhost:28084
  prefix: ./teaching-ocean/upload

---
# dev
spring:
  config:
    activate:
      on-profile: dev
  datasource:
    url: jdbc:log4jdbc:mysql://dev-readingocean-db-01.ccemsdd2ijls.ap-northeast-2.rds.amazonaws.com:3306/redutec?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&useSSL=false&allowMultiQueries=true&useInformationSchema=true&autoReconnect=true
    username: "root"
    password: "readingocean2022"