# server
server:
  port: 28084
# Spring
spring:
  application:
    name: teaching-ocean
  config:
    activate:
      on-profile: local
  datasource:
    url: jdbc:log4jdbc:mysql://127.0.0.1:3306/READING_OCEAN?characterEncoding=UTF-8&serverTimezone=Asia/Seoul&noAccessToProcedureBodies=true&allowPublicKeyRetrieval=true&useSSL=false&allowMultiQueries=true&useInformationSchema=true&autoReconnect=true
    username: "redutec"
    password: "readingocean2022"
    driver-class-name: net.sf.log4jdbc.sql.jdbcapi.DriverSpy
    hikari:
      maximum-pool-size: 20
      connection-timeout: 30000
      leak-detection-threshold: 30000
      maxLifetime: 1800000
      idleTimeout: 600000
  jpa:
    database-platform: org.hibernate.dialect.MySQL8Dialect
    hibernate:
      ddl-auto: validate
    show-sql: true
# Security
jwt:
  secret: "re@ding0ce@n#123AdminJsonWebTokenSecret"
  access-token-expiration: 60000
  refresh-token-expiration: 37600000
# Custom
front-end-server: 127.0.0.1